config/routes.rb
Rails.application.routes.draw do
    get 'ingredients/edit'
    get 'ingredients/update'
    root to: 'page#home'
    devise_for :users, :controllers => { omniauth_callbacks: "users/omniauth_callbacks" }

    resources :ingredients
    resources :comments
    resources :recipes 

    resources :categories do 
        resources :recipes
    end

    resources :recipes do 
        resources :comments
    end

end

app/models/recipe.rb
class Recipe < ApplicationRecord
	include Filterable

	has_one_attached :image
	belongs_to :user
	belongs_to :category
	has_many :comments, dependent: :destroy
	has_many :recipe_ingredients, dependent: :destroy
	has_many :ingredients, through: :recipe_ingredients, dependent: :destroy
	
	# validates :image, presence: true
	validates :name, presence: true, uniqueness: {:scope => [:user_id, :category_id]}
	validates :number_of_persons, presence: true
	validates :directions, presence: true 
	validate :ingredient_names
	before_validation :name_capitalizer

	scope :find_recipes_by_name, -> (name) { where("name like ?", "#{name.capitalize}%")}
	scope :find_recipes_by_serving, -> (number_of_persons) { where number_of_persons: number_of_persons }
	

	def recipe_ingredients_attributes=(recipe_ingredients_hash)
		recipe_ingredients_hash.values.each do |recipe_ingredient|
			recipe = Recipe.find_by(id: recipe_ingredient[:recipe_id])
			rec_ingredient = RecipeIngredient.find_by(id: recipe_ingredient[:id])
			ingredient = Ingredient.find_by(id: recipe_ingredient[:ingredient_attributes][:id])
			if recipe && rec_ingredient && ingredient
				rec_ingredient.update(amount: recipe_ingredient[:amount])
				ingredient.update(name: recipe_ingredient[:ingredient_attributes][:name])
			else
				self.recipe_ingredients.build(recipe_ingredient)
			end
		end
	end
	
	def ingredient_names 
		self.recipe_ingredients.map(&:ingredient_id)
		if ingredient_ids != ingredient_ids.uniq
			self.errors.add(:recipe_ingredients, "Ingredient Name Should Appear Once!")
		end
	end

	def self.list_by_category 
		all.group_by(&:category)
	end
	
	def self.desc_listing
		all.order(created_at: :desc)
	end

	def self.order_by_name
		all.order(name: :asc)
	end


	private 

	def name_capitalizer 
		self.name = self.name.capitalize 
	end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
    before_action :find_recipe, only: [:show, :edit, :update, :destroy]

    def index
        @recipes = Recipe.filter(params.slice(:find_recipes_by_name, :find_recipes_by_serving)).desc_listing
        unless @recipes.present?
            redirect_to recipes_path, notice: "Record Not Found"
        end
    end 

    def new 
        @recipe = Recipe.new 
        4.times do 
            @recipe.recipe_ingredients.build.build_ingredient
        end
    end 

    def create 
        @recipe = current_user.recipes.build(recipe_params)
        if @recipe.save
            redirect_to recipe_path(@recipe.id), notice: "Recipe Successfully Created" 
        else 
            render :new
        end 
    end 

    def show
        redirect_to recipes_path, notice: "Record not found!" if @recipe.nil?
    end 

    def edit 
        redirect_to recipes_path, notice: "Record not found!" if @recipe.nil?
    end 

    def update 
        if @recipe.update(recipe_params) 
            redirect_to recipe_path(@recipe), notice: "Recipe Successfully Updated" 
        else 
            render :edit 
        end 
    end 

    def destroy  
        if @recipe.destroy
            redirect_to recipes_path, notice: "Successfully deleted recipe"
        end
    end 

    private 

    def find_recipe 
        @recipe = Recipe.find_by(id: params[:id])
    end 

    def recipe_params
        params.require(:recipe).permit(:name, :directions, :image, :number_of_persons, :category_id, :recipe_ingredients_attributes => [:id, :recipe_id, :amount, :ingredient_attributes => [:id, :name]])
    end 

end

app/helpers/recipes_helper.rb
module RecipesHelper

    def created_date_of(recipe)
        recipe.created_at.strftime("%A, %b %e, at %l:%M %p")
    end

    def updated_date_of(recipe)
        recipe.updated_at.strftime("%A, %b %e, at %l:%M %p")
    end
    
end

app/views/recipes/_errors.html.erb
<% if recipe.errors.any? %>
    <div id="error_explanation">
        <h2>
            <%= pluralize(recipe.errors.count, "error") %>
            prohibited this recipe from being saved:
        </h2>
        <ul>
            <% recipe.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/recipes/_form.html.erb
<%= form_for recipe do |f| %>
    
    <div class="field">
        <%= f.label "CategorecIngres" %> <br>
        <%= f.collection_select :category_id, Category.all, :id, :name, prompt: "Pick a Category" %> 
    </div><br>
       
    <div class="field">
        <%= f.label "Add an Image" %> 
        <%= f.file_field :image %>
    </div>
    
    <div class="field">
        <%= f.label :name %> 
        <%= f.text_field :name, placeholder: "Enter a Recipe" %>
    </div>

    <div class="field">
        <%= f.label "Servings" %> 
        <%= f.number_field :number_of_persons, placeholder: "Enter a Number" %>
    </div>
    
    <fieldset>
        <legend><strong>Ingredients</strong></legend>
            <%= f.fields_for :recipe_ingredients do |recIngr_builder| %>
                <%= recIngr_builder.hidden_field :recipe_id, value: recipe.id %>
                <%= recIngr_builder.fields_for :ingredient do |ingr_builder| %> 
                    <div class="field">
                        <%= ingr_builder.text_field :name, placeholder: "Ingredient Name" %>
                    </div>
                <% end %>  
                <div class="field">
                    <%= recIngr_builder.text_field :amount, placeholder: "Quantity" %>
                </div>
            <% end %>
     </fieldset>    
        
    <div class="field">
        <%= f.label :directions %> <br>
        <%= f.text_area :directions, cols: "50", rows: "5" %>
    </div>      
    
    <%= f.submit %>
<% end %>

app/views/recipes/edit.html.erb
<%= render partial: "errors", locals: {recipe: @recipe} %>

<h1>Edit</h1>

<%= render partial: "form", locals: {recipe: @recipe} %>

app/views/recipes/index.html.erb
<%= form_tag recipes_path, method: :get do %>
<p>
    <%= text_field_tag :find_recipes_by_name, params[:find_recipes_by_name], placeholder: "Search by Names" %>
    <%= submit_tag "Search", name: nil %>
</p>
<% end %> 

<h4>Or</h4>

<%= form_tag recipes_path, method: :get do %>
<p>
    <%= text_field_tag :find_recipes_by_serving, params[:find_recipes_by_serving], placeholder: "Search by Servings" %>
    <%= submit_tag "Search", name: nil %>
</p>
<% end %>


<div class="row">
    <% @recipes.each do |recipe| %>
        <div class="column">
            <%= link_to recipe.name, recipe_path(recipe) %> 
            <% if recipe.image.attached? %>
                <image src="<%=(url_for(recipe.image)) %>" style="width:100%;">
            <% end %> 
            <strong>by: <%= mail_to recipe.user.email %></strong> <br>
            <strong><%= link_to pluralize(recipe.comments.count, "Review"), recipe_comments_path(recipe) %></strong>
        </div>
    <% end %>
</div>

app/views/recipes/new.html.erb
<%= render partial: "errors", locals: {recipe: @recipe} %>

<%= link_to "Back", recipes_path %> <br>

<h1>Create A New Recipe</h1>

<%= render partial: "form", locals: {recipe: @recipe} %>

app/views/recipes/show.html.erb
<br> Created on <%= created_date_of(@recipe) %>

<h3 style="color: red"><%= @recipe.name %> </h3>

<% if @recipe.image.attached? %>
    <image src="<%=(url_for(@recipe.image)) %>">
<% end %>

<ul>
    <li><strong>Servings: <%= @recipe.number_of_persons%></strong></li>
</ul>

<h3 style="color: red">Ingredients</h3>
<ul>
    <% @recipe.recipe_ingredients.each do |rec_ing| %>
    <table>
        <thead>
            <th><%= rec_ing.ingredient.name %></th>
        </thead>
        <tbody>
            <td><%= rec_ing.amount %></td>
        </tbody>
    </table>
    <% end %>
</ul>

<h3 style="color: red">Cooking Directions</h3>
<p>
    <%= @recipe.directions %> 
</p>

<h3 style="color: red;">Comments</h3>
<% @recipe.comments.each do |comment| %>
    <% if comment.user.username.present? %>
        <strong><%= comment.user.username.capitalize %></strong> 
        <ul>
            <li> <%= comment.content %></li>
        </ul>
    <% else %> 
        <strong><%= comment.user.name.capitalize  %></strong> <br>
        <ul>
            <li><%= comment.content %></li>
        </ul> 
    <% end %> 

    <% if comment.user == current_user %>
        <%= link_to "Edit", edit_comment_path(comment) %> 
        <%= button_to "x", comment_path(comment), method: :delete, class: "destroy", data: {confirm: "Are you sure?" } %>
    <% end %> 
<% end %>

<%= render partial: "comments/form", locals: { comment: @recipe.comments.build } %>


<% if @recipe.user == current_user %>
    <%= link_to "Back", recipes_path %> <br>
    <%= link_to "Edit", edit_recipe_path(@recipe) %> <br>
    <%= link_to "Delete", recipe_path(@recipe), method: :delete, data: {confirm: "Are you sure?" } %> <br>
<% else %>
    <%= link_to "Back", recipes_path %> <br>
<% end %>