config/routes.rb
Rails.application.routes.draw do
    get 'ingredients/edit'
    get 'ingredients/update'
    root to: 'page#home'
    devise_for :users, :controllers => { omniauth_callbacks: "users/omniauth_callbacks" }

    resources :ingredients
    resources :comments
    resources :recipes 

    resources :categories do 
        resources :recipes
    end

    resources :recipes do 
        resources :comments
    end

end

app/models/category.rb
class Category < ApplicationRecord
    has_many :recipes

    validates :name, presence: true, uniqueness: true

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :find_category, only: [:show, :edit, :update, :destroy]
    before_action :redirect_unless_admin, only: [:new, :create, :edit, :update, :destroy]

    def index
        @categories = Category.all
        @categories_recipes = Recipe.list_by_category 
    end

    def new 
        @category = Category.new 
    end 

    def create 
        @category = Category.new(category_params) 
        if @category.save 
            redirect_to category_path(@category), notice: "Category Successfully Created" 
        else
            render :new 
        end
    end 

    def show  
    end

    def edit 
    end 

    def update 
        if @category.update(category_params)
            redirect_to category_path(@category), notice: "Category Successfully Updated" 
        else 
            render :edit 
        end
    end 

    def destroy 
        @category.destroy 
        redirect_to categories_path, notice: "Category Successfully Deleted" 
    end

    private 

    def find_category 
        @category = Category.find_by(id: params[:id])
    end

    def category_params
        params.require(:category).permit(:name)
    end 

    def redirect_unless_admin
        redirect_to categories_path unless current_user.admin 
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.submit %>
<% end %>

app/views/categories/edit.html.erb
<%= render partial: 'recipes/errors', locals: {recipe: @category} %>

<h1>Edit</h1>

<%= render "form" %>

app/views/categories/index.html.erb
<%= link_to "Back", recipes_path %>

<% if current_user.admin %>
    <%= link_to "New category", new_category_path %>
<% end %>

<% @categories.each.with_index(1) do |category, index| %>
    <% if current_user.admin %>
        <ul>
            <%= index %>- <strong><%= category.name %></strong> <br>
            <%= link_to "Edit", edit_category_path(category) %> <%= link_to "Delete", category_path(category), method: :delete, class: "destroy", data: {confirm: "Are you sure?"} %>
        </ul>              
    <% end %>
<% end %> <br> <br>

<% @categories_recipes.each do |category, recipes| %>
    <h2 style="color: red;"><%= category.name if category %></h2> 
    <strong>Total: <%= pluralize(category.recipes.count, "Recipe") %></strong> 
    <ul>
        <% recipes.each do |recipe| %>
            <p>
                <li><%= link_to recipe.name, category_recipe_path(recipe.category_id, recipe) %> </li>
                <strong>by: <%= recipe.user.name || recipe.user.username %></strong>
            </p>
        <% end %>
    </ul>
<% end %>

app/views/categories/new.html.erb
<%= render partial: 'recipes/errors', locals: {recipe: @category} %>
<h1>Create a New Category</h1>

<%= render "form" %>

app/views/categories/show.html.erb
<%= link_to "Back", categories_path %>

<h1>Category</h1>
<p>
    <strong><%= @category.name %></strong> 
</p>