config/routes.rb
Rails.application.routes.draw do
    get 'ingredients/edit'
    get 'ingredients/update'
    root to: 'page#home'
    devise_for :users, :controllers => { omniauth_callbacks: "users/omniauth_callbacks" }

    resources :ingredients
    resources :comments
    resources :recipes 

    resources :categories do 
        resources :recipes
    end

    resources :recipes do 
        resources :comments
    end

end

app/views/layouts/_alerts.html.erb
<h3 class="notice" style="color: red;"><%= notice %></h3>
<h3 class="alert" style="color: red;"><%= alert %></h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipesSharing20</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

    <body>
        <nav class="nav_bar">
            <ul>
                <% if current_user %>
                    <li><%= link_to "Edit Profile", edit_user_registration_path(current_user) %></li>
                    <li style="float: right;"><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
                    <li><%= link_to "Recipes", recipes_path %></li> 
                    <li><%= link_to "See by Category", categories_path %></li>
                    <li><%= link_to "New Recipe", new_recipe_path %></li>
                <% else %>
                    <li><%= link_to "Log in", new_session_path(resource_name) %></li>
                    <li><%= link_to "Sign up", new_registration_path(resource_name) %></li>
                <% end %>
            </ul>
        </nav>
            <%= render 'layouts/alerts' %>
            <%= yield %>
    </body>
</html>